server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: spring-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**
        - id: ai-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/v2/**
